OPENAI_API_KEY = "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"
CLIENT_ID = "3f1618e4-3ebd-4baa-b327-439abad06a04"
AUTHORITY = "https://login.microsoftonline.com/consumers"
SCOPES = "Files.Read.All"